dist: trusty
sudo: false
language: php

php:
  - '7.0'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: travis_retry composer install

script:
  - ./vendor/bin/phpunit --coverage-html coverage --whitelist src test
